mail:
  image: interlegis/mailbox
  #build: mail
  env_file:
    - settings.env
  links:
    - mysql
    - opendkim
    - spamassassin
  volumes:
    - "ilmail_certs:/etc/certs"
    - "ilmail_vmail:/var/vmail"
    - "ilmail_spamassassin:/var/spamassassin"
  ports:
    - "25:25"
    - "587:587"
    - "143:143"

opendkim:
  image: interlegis/opendkim
  env_file:
    - settings.env
  expose:
    - "8891"
  volumes:
    - "ilmail_certs:/etc/certs"

spamassassin:
  image: interlegis/spamassassin
  expose:
    - "783"
  volumes:
    - "ilmail_vmail:/var/vmail"
    - "ilmail_spamassassin:/var/spamassassin"

memcache:
  image: memcached
  expose:
    - "11211"

# MySQL server
mysql:
  image: interlegis/mariadb-slim
  environment:
    MYSQL_ROOT_PASSWORD: A_Really_Strong_Password
  volumes:
    - "ilmail_mysql:/var/lib/mysql"

# ViMbAdmin
vimbadmin:
  #build: vimbadmin
  image: interlegis/vimbadmin
  links:
    - mysql
    - memcache
    - mail
  volumes:
    - "ilmail_certs:/etc/certs"
  env_file:
    - settings.env

mbadmin:
  image: nginx
  links:
    - vimbadmin
  volumes_from:
    - vimbadmin
  ports:
    - "8081:80"

# Roundcube
roundcube:
  image: interlegis/roundcube
  #build: roundcube
  links:
    - mysql
    - memcache
    - mail
  env_file:
    - settings.env
  volumes:
    - "ilmail_certs:/etc/certs"

webmail:
  image: nginx
  links:
    - roundcube
  volumes_from:
    - roundcube
  ports:
    - "8080:80"
